### ISSUE TITLE
Warnings when runing sbt and sbt test

### ISSUE THREAD

**Issue by kdbeall** [playframework/play-java-angular-seed#1]
`sbt`
`
[warn] Found version conflict(s) in library dependencies; some are suspected to be binary incompatible:
[warn] 	* org.webjars:webjars-locator-core:0.33 is selected over 0.32
[warn] 	    +- com.typesafe:npm_2.12:1.2.1                        (depends on 0.32)
[warn] 	    +- com.typesafe.sbt:sbt-web:1.4.3 (scalaVersion=2.12, sbtVersion=1.0) (depends on 0.32)
[warn] 	* org.codehaus.plexus:plexus-utils:3.0.17 is selected over {2.1, 1.5.5}
[warn] 	    +- org.apache.maven:maven-settings:3.2.2              (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-repository-metadata:3.2.2   (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-aether-provider:3.2.2       (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-model:3.2.2                 (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-core:3.2.2                  (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-artifact:3.2.2              (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-settings-builder:3.2.2      (depends on 3.0.17)
[warn] 	    +- org.apache.maven:maven-model-builder:3.2.2         (depends on 3.0.17)
[warn] 	    +- org.sonatype.plexus:plexus-sec-dispatcher:1.3      (depends on 1.5.5)
[warn] 	    +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5  (depends on 2.1)
[warn] 	* com.google.guava:guava:23.0 is selected over {10.0.1, 16.0, 20.0}
[warn] 	    +- io.methvin:directory-watcher:0.3.2                 (depends on 23.0)
[warn] 	    +- com.fasterxml.jackson.datatype:jackson-datatype-guava:2.8.8 (depends on 10.0.1)
[warn] 	    +- org.eclipse.sisu:org.eclipse.sisu.plexus:0.0.0.M5  (depends on 10.0.1)
[warn] 	    +- com.spotify:docker-client:8.9.0                    (depends on 10.0.1)
[warn] Run 'evicted' to see detailed eviction warnings
`

`sbt run`

`
[warn] 	* com.google.guava:guava:22.0 is selected over {19.0, 20.0}
[warn] 	    +- com.typesafe.play:play_2.12:2.6.9                  (depends on 22.0)
[warn] 	    +- org.reflections:reflections:0.9.11                 (depends on 20.0)
[warn] 	    +- com.google.inject:guice:4.1.0                      (depends on 19.0)
[warn] 	* com.typesafe.akka:akka-stream_2.12:2.5.8 is selected over 2.4.20
[warn] 	    +- com.typesafe.play:play-streams_2.12:2.6.9          (depends on 2.5.8)
[warn] 	    +- com.typesafe.akka:akka-http-core_2.12:10.0.11 ()   (depends on 2.4.20)
[warn] 	* com.typesafe.akka:akka-actor_2.12:2.5.8 is selected over 2.4.20
[warn] 	    +- com.typesafe.akka:akka-slf4j_2.12:2.5.8 ()         (depends on 2.5.8)
[warn] 	    +- com.typesafe.akka:akka-stream_2.12:2.5.8 ()        (depends on 2.5.8)
[warn] 	    +- com.typesafe.play:play_2.12:2.6.9                  (depends on 2.5.8)
[warn] 	    +- com.typesafe.akka:akka-parsing_2.12:10.0.11 ()     (depends on 2.4.20)
[warn] Run 'evicted' to see detailed eviction warnings
`

**Comment by yohangz** [comment]
I've tried all above commands with a fresh copy of starter kit and everything seems to be working as expected without any warnings. Seems like you are experiencing this issue due to incompatible dependencies which you've introduced. Make sure that there are no version conflicts when you are introducing new dependencies.

Please note that mentioned issue is not related to this seed project.

**Comment by sanuradhag** [comment]
In ubuntu 16.04 starter kit runs without any issue as expected. 
![aaa-qqq](https://user-images.githubusercontent.com/24251976/36295042-c8e7652e-130a-11e8-86fa-2fe4feb003ee.png)

**Comment by kdbeall** [comment]
Thanks @yohangz turns out my sbt version was out of date.
