### ISSUE TITLE
Why you kept one controller in scala ? Is this required ?

### ISSUE THREAD

**Issue by mainpal1** [playframework/play-java-angular-seed#3]
https://github.com/yohangz/java-play-angular-seed/tree/master/app/controllers

one controller is in scala  	**FrontendController.scala**

**Comment by yohangz** [comment]
There is no specific reason, actually I worked on [Scala Play seed project](https://github.com/yohangz/scala-play-angular-seed) first and reused the same frontend controller code here. Beauty of play framework is that you can seamlessly use both Scala and Java code within the same project.
