### ISSUE TITLE
How to work with Docker?

### ISSUE THREAD

**Issue by playtowork** [playframework/play-java-angular-seed#5]
I have a Play framework project (2.6.19). I have integrated Angular7, in the way shown in this repo. So if I run `sbt "project frontend" run` or `sbt "project frontend" dist`, then the corresponding hooks for setting up Angular are invoked, and the app is able to run correctly.

But my Play project is Dockerized (via https://www.scala-sbt.org/sbt-native-packager/formats/docker.html). When I run `sbt "project frontend" docker:publish`, the usual binary for the Play app is created and Docker uses that for the entrypoint. However, none of the hooks for building the Angular project are invoked. When I access the app after pushing the Docker image, it runs as before (Angular is not running).

Is there a way I can insert a hook so that the Angular code is built, upon `sbt "project frontend" docker:publish` or `sbt "project frontend" docker:publishLocal`? I was thinking perhaps `sbt "project frontend" docker:publish` would be calling `sbt "project frontend" dist` under the hood, but apparently it is not.

**Comment by yohangz** [comment]
You have to set a task dependency to call ```dist``` as a dependent task of ```docker:publish``` 

refer ```ui-build.sbt``` last 3 lines of code

**Comment by playtowork** [comment]
Thanks. It worked. Specifically, I added the following lines to `ui-build.sbt`:
```
Docker / publish := (Docker / publish dependsOn `ui-prod-build`).value
Docker / publishLocal := (Docker / publishLocal dependsOn `ui-prod-build`).value
```
